[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_project"
version = "0.1.0"
description = "A cool modeling project."
authors = [
  { name="Your Name", email="your@email.com" }
]
dependencies = [
  "pandas>=2.0",
  "numpy>=1.22",
  "scikit-learn>=1.3",
  "matplotlib",
  "seaborn"
]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"

[tool.mypy]
python_version = "3.10"
strict = true
